# Generated by Django 5.1.4 on 2025-05-23 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOfferingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_length', models.IntegerField(choices=[(3600, 'HOUR'), (1900, 'QUARTER')], default=3600)),
                ('values', models.JSONField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 5, 23, 15, 40, 6, 93495, tzinfo=datetime.timezone.utc), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailyOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('entries', models.ManyToManyField(to='offering.dailyofferingentry')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='offering_da_date_779078_idx')],
            },
        ),
    ]
