# Generated by Django 5.1.4 on 2025-05-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days_offset', models.IntegerField(default=1)),
                ('gate_close_time', models.TimeField()),
                ('result_time', models.TimeField()),
                ('timezone_name', models.CharField(default='CET', max_length=100)),
            ],
        ),
    ]
